### ISSUE TITLE
:busts_in_silhouette: expand `meta` tag inclusion, facets

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/jemison#28]
# At a glance

[comment]: # "Begin with a short summary so intent can be understood at a glance."

[comment]: # "In order to: some objective or value to be achieved"
[comment]: # "as a: stakeholder"
[comment]: # "I want: some new feature"

**In order to** support some existing search features
**as a** developer
**I want** to pull in the existing metadata that search.gov supports

# Acceptance Criteria

We use [DRY](https://docs.behat.org/en/latest/user_guide/writing_scenarios.html#backgrounds) [behavior-driven development](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications) wherever possible.

[comment]: # "ACs should be clearly demoable/verifiable whenever possible."
[comment]: # "Given: the initial context at the beginning of the scenario"
[comment]: # "when: the event that triggers the scenario"
[comment]: # "then: the expected outcome(s)"
[comment]: # "Repeat scenarios as needed, or repeat behaviors and lists within a scenario as needed."

[comment]: # "The scenario should be a short, plain language description."
[comment]: # "Feeling repetitive? Apply the DRY (Don't Repeat Yourself) principle!"

...

[comment]: # "Each task should be a verifiable outcome"
```[tasklist]
### then... 
- [ ] [a thing happens]
```

### Shepherd

[comment]: # "@ mention shepherds as we move across the board."

* UX shepherd: 
* Design shepherd: 
* Engineering shepherd: 

# Background

https://search.gov/indexing/metadata.html

Looking at https://www.nasa.gov/, we can see how they have some facets (e.g. `Missions`). Those are captured throughout the site as various `meta` tags.

These can easily be slurped in; this implies a few changes.

1. The `extract` component, along with a `content` field int he JSON object in S3, will end up with several more fields for the metadata.
2. The `pack` component needs to expand the table design. We currently throw all of the content into the `site_index`. Now, I need to think about something approaching a v1 data model for the search tables. This would include a column for various kinds of metadata, possibly break out some tags (e.g. have `h1` content separate from the bulk `content` pull?), and so on.

The `serve` component does not *yet* need to change, but what is true is that the SQL that drives the query (in the `sqlc` wrapper) can be updated to use the [bm25() function to apply weighting](https://sqlite.org/fts5.html#the_bm25_function) to the new columns/tables/data. Again, not a big deal, but that will be the final step to improving the ranking/quality of the search results.

This is ultimately a necessary step to support UX work where we improve how we index/retrieve results. So.

All of this is _post `fetch`_. That is, none of it is a blocker to obtaining the content. Improvements to `extract` and `pack` can be applied to content in the S3 bucket without having to re-fetch. It will still take _time_, because we could end up talking about re-extracting/re-packing many millions of objects, but it does not require the kind of calendar time that re-fetching content will take.

# Security Considerations

Required per [CM-4](https://nvd.nist.gov/800-53/Rev4/control/CM-4).

[comment]: # "Our SSP says 'The team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.'"
[comment]: # "Please do not remove this section without care."
[comment]: # "Note any security concerns that might be implicated in the change. 'None' is OK, but we must be explicit here."

None.

---

<details>
  <summary>Process checklist</summary>
  
- [ ] Has a clear story statement
- [ ] Can reasonably be done in a few days (otherwise, split this up!)
- [ ] Shepherds have been identified
- [ ] UX youexes all the things
- [ ] Design designs all the things
- [ ] Engineering engineers all the things
- [ ] Meets acceptance criteria
- [ ] Meets [QASP conditions](https://derisking-guide.18f.gov/qasp/)
- [ ] Presented in a review
- [ ] Includes screenshots or references to artifacts
- [ ] Tagged with the sprint where it was finished
- [ ] Archived

### If there's UI...
- [ ] Screen reader - Listen to the experience with a screen reader extension, ensure the information presented in order
- [ ] Keyboard navigation - Run through acceptance criteria with keyboard tabs, ensure it works. 
- [ ] Text scaling - Adjust viewport to 1280 pixels wide and zoom to 200%, ensure everything renders as expected. Document 400% zoom issues with USWDS if appropriate.

</details>

**Comment by jadudm** [comment]
Needs UX. Closing until we drive things like this forward with user stories.
