### ISSUE TITLE
Onboarding checklist for Sue

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/jemison#29]
**Instructions for the issue creator:** 
1. Fill in the GitHub username of the new person (if known) and the name of the onboarding buddy. 
2. Remove the horizontal line below and everything above it (these instructions).

---

# Welcome to the team **TBD GH USERNAME**

{ONBOARDING BUDDY'S GH USERNAME} will be your onboarding buddy and can help you if you get stuck on any of the steps in the checklist below. There's also a separate checklist that your onboarding buddy will tackle!

## For you

- [ ] Review [the project README](https://github.com/GSA-TTS/jemison/docs/README.md)
- [ ] Join/get added to the team Slack channels
- [ ] Review our [process documentation](https://github.com/GSA-TTS/jemison/docs/process/)
- [ ] Get access to our GitHub repositories
  - [ ] If you're not already a member of BOTH the [GSA](https://github.com/orgs/GSA/people) and [GSA-TTS](https://github.com/orgs/GSA-TTS/people) GitHub organizations, [follow the process outlined here](https://github.com/GSA/GitHub-Administration#joining-the-gsa-enterprise-organization), requesting access to the appropriate org(s). When it's time to send the mail, look up the Product Lead (see [the staffing list](https://docs.google.com/document/d/1g8nYqYS_ifFlZB-DBgfeSoJRMB__EqWsmLnacyk-bDI/edit#heading=h.us8xylqg455c)) then start with this template, mailing from your GSA email address:

    ```text
    To: gsa-github.support@gsa.gov
    Cc: [the search lead]
    Subject: GSA and GSA-TTS GitHub organization membership
    Body:
    [Edit the following text to put in your GitHub username and your GSA email address, then remove this instruction text.]
    Please add my GitHub account (https://github.com/myusername) to the following GitHub organizations:
    - https://github.com/GSA
    - https://github.com/GSA-TTS
    
    I will be working on the FAC project:
    - https://github.com/GSA-TTS/jemison
    
    I have cc'd the search.gov lead for awareness.
        
    Thank you!
    ```        
    - (Note this step could take a few days; humans handle these requests.)
  - [ ] Once you are added to the GSA-TTS org, ask [the person(s) with the "Maintainer" role to add you to the `jemison-team` team](https://github.com/orgs/GSA-TTS/teams/jemison-team/members). This will grant you read/write access to our repositories.
  - [ ] Have the team calendar owner share the calendar invite link to our new team member.

## For your onboarding buddy

Note: If you're not able to do any of these yourself, you're still responsible for making sure that the right person makes them happen!
