### ISSUE TITLE
:building_construction: automated deployments

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/jemison#55]
## Problem
[comment]: # "What problem are we solving with? Is this epic part of the planned features, and which ones?"

We want deployments to be repeatable and automated.

## How did we discover this problem?
[comment]: # "How did this problem originate? If it was revealed through user feedback, how was that feedback received and from whom?"

The previous search deployment involved a combination of 1) manual and automated steps, using 2) a combination of deployment tools. This made it difficult for *one person* to *push a button* and get a reliable and repeatable deploy.

## Job Story(s)

When I *press the deploy button in GH Actions*, I want to *sit back and drink coffee* so I can *watch my deployment TV*.

## What are we planning to do about it?

[comment]: # "What is the scope of the design and engineering work required for this project?"
[comment]: # "Along the way, this epic will be linked with issues and pull requests"

We will be deploying to Cloud.gov. We should get `dev` working first, and get our S3 sync/access controls in place. Then, we can do `prod`, and then `staging` last.

## What are we not planning to do about it?
[comment]: # "What items have been considered but may fall out of the scope of design and engineering work for this project?"

We're... not planning on not doing it.

## How will we measure success?
[comment]: # "Are there a set of quantifiable metrics that we can surface once the work has been completed in order to determine how successful our solution was?"

```[tasklist]
### Tasks
- [ ] Set up a TF deploy for `dev`, `staging`, and `prod`
- [ ] Automate the `dev` deploys on every push to `main`
- [ ] Automate the `staging` deploys as a daily action
- [ ] Allow team members to trigger `prod` deploys by cutting a release in GH
- [ ] The TF state should be stored in an S3 bucket (so we do not have sync issues)
- [ ] Access control to Cloud.gov should be managed via a static file in GH (see [this repo](https://github.com/GSA-TTS/FAC/blob/main/terraform/meta/config.tf) for an example)
```
